kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
  - host: tariqsheikh.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caddy-svc
            port:
              number: 80
